spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: !
    url: jdbc:mysql://rm-uf60tde45podskc50ho.mysql.rds.aliyuncs.com:3306/id-blog-user

  application:
    name: user-server

server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/