spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jaon2020!

  application:
    name: user-server

server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5556/eureka/